#define PIN_LED PA_10
#define PIN_LED_GND NO_PIN

#define PIN_PWR NO_PIN
#define PIN_P0 NO_PIN
#define PIN_P1 NO_PIN

#define PIN_AMOSI PB_7
#define PIN_ASCK PA_0

#define UART_PIN PB_6
#define UART_PIN_AF LL_GPIO_AF_0
#define USART_IDX 1

#define PIN_BL_LED PIN_LED
#define PIN_BL_PERIOD 300

#define BOARD_STARTUP_CODE LL_SYSCFG_EnablePinRemap(LL_SYSCFG_PIN_RMP_PA12);
#define RESET_AS_GPIO

#define DISABLE_SWCLK_FUNC